services:
  signbridge_api:
    image: tamb2203579/voya_api:latest
    container_name: signbridge_api
    restart: always
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - signbridge_redis
    networks:
      - ec2_global_network

  signbridge_redis:
    image: redis:6.2
    container_name: signbridge_redis
    restart: always
    expose:
      - "6379"
    networks:
      - ec2_global_network

networks:
  ec2_global_network:
    external: true